"""Constants for Agent Skills."""

MAX_SKILL_NAME_LENGTH = 64
MAX_DESCRIPTION_LENGTH = 1024
MAX_COMPATIBILITY_LENGTH = 500
MAX_LICENSE_LENGTH = 100
MAX_ALLOWED_TOOLS_LENGTH = 1024
MAX_METADATA_KEY_LENGTH = 64
MAX_METADATA_VALUE_LENGTH = 1024
